import React, { useState } from 'react';
import { 
  ArrowRight, Check, Sparkles, TrendingUp, Layers, 
  Instagram, ShoppingBag, Globe, Video, Camera, 
  Facebook, Youtube, Plus, Minus, Monitor, Share2,
  RefreshCw, ChevronRight, Zap, Eye
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { Button } from '../ui/button';
import { Card, CardContent } from '../ui/card';
import { Badge } from '../ui/badge';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '../ui/sheet';
import { useBrandShoot } from '../../context/BrandShootContext';
import { ImageWithFallback } from '../figma/ImageWithFallback';

// --- Icons Map ---
const ChannelIcons: Record<string, React.ElementType> = {
  Instagram: Instagram,
  Facebook: Facebook,
  YouTube: Youtube,
  TikTok: Share2,
  Pinterest: Layers,
  Shopify: ShoppingBag,
  Amazon: ShoppingBag,
  Website: Monitor
};

interface CampaignSummaryProps {
  onNavigate: (screen: string) => void;
}

export function CampaignSummary({ onNavigate }: CampaignSummaryProps) {
  const { 
    campaignPlan, 
    isAdjustMode, 
    setAdjustMode,
    updatePackCount,
    updateAsset,
    assets: contextAssets
  } = useBrandShoot();
  
  const [swappingAssetIndex, setSwappingAssetIndex] = useState<number | null>(null);

  if (!campaignPlan) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#FDFBF9] font-serif text-gray-400">
        Loading campaign plan...
      </div>
    );
  }

  const { strategy, ads, pricing, channelPacks, assets } = campaignPlan;

  const handleAssetSwap = (newUrl: string) => {
    if (swappingAssetIndex !== null) {
      updateAsset(swappingAssetIndex, newUrl);
      setSwappingAssetIndex(null);
    }
  };

  const renderSwapOverlay = (index: number, children: React.ReactNode, className?: string) => (
    <div className={`relative group cursor-pointer ${className}`} onClick={() => setSwappingAssetIndex(index)}>
      {children}
      <div className="absolute inset-0 bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center z-20 pointer-events-none">
         <div className="bg-white/90 backdrop-blur-md text-[#111111] px-4 py-2 rounded-full flex items-center gap-2 text-xs font-bold uppercase tracking-wider transform translate-y-4 group-hover:translate-y-0 transition-transform shadow-lg">
           <RefreshCw className="w-3 h-3" />
           Swap Visual
         </div>
      </div>
    </div>
  );

  // --- Animation Variants ---
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: { 
      opacity: 1,
      transition: { staggerChildren: 0.1, delayChildren: 0.2 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: "easeOut" } }
  };

  return (
    <div className="min-h-screen bg-[#FAFAFA] pb-32 font-sans text-[#111111] overflow-x-hidden selection:bg-indigo-100 selection:text-indigo-900">
      
      {/* --- HEADER --- */}
      <div className="sticky top-0 z-40 bg-white/80 backdrop-blur-xl border-b border-gray-100/50">
        <div className="max-w-[1600px] mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-[#111111] text-white rounded-lg flex items-center justify-center">
              <Sparkles className="w-4 h-4" />
            </div>
            <div>
              <h1 className="font-serif text-lg font-medium text-[#111111] leading-none">Campaign Plan</h1>
              <span className="text-[10px] text-gray-500 uppercase tracking-widest font-medium">Generated by Cura AI</span>
            </div>
          </div>

          {/* Mode Toggle */}
          <div className="bg-[#F4F4F5] p-1 rounded-lg flex items-center">
            <button
              onClick={() => setAdjustMode(false)}
              className={`px-4 py-1.5 rounded-md text-xs font-bold transition-all ${
                !isAdjustMode 
                  ? 'bg-white text-[#111111] shadow-sm' 
                  : 'text-gray-500 hover:text-gray-900'
              }`}
            >
              Overview
            </button>
            <button
              onClick={() => setAdjustMode(true)}
              className={`px-4 py-1.5 rounded-md text-xs font-bold transition-all ${
                isAdjustMode 
                  ? 'bg-white text-[#111111] shadow-sm' 
                  : 'text-gray-500 hover:text-gray-900'
              }`}
            >
              Adjust
            </button>
          </div>
        </div>
      </div>

      <motion.div 
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="max-w-[1600px] mx-auto px-4 md:px-8 pt-8 space-y-12 md:space-y-16"
      >

        {/* --- SECTION 1: HERO (Product Sales Campaign) --- */}
        <motion.div variants={itemVariants}>
          <div className="relative rounded-[32px] overflow-hidden bg-[#1E1E24] text-white min-h-[400px] flex flex-col md:flex-row items-center shadow-2xl shadow-indigo-900/10">
             
             {/* Content Side */}
             <div className="flex-1 p-8 md:p-16 relative z-10 flex flex-col justify-center h-full">
                <Badge className="self-start bg-white/10 text-white border-0 mb-6 backdrop-blur-md px-3 py-1 text-xs font-medium tracking-wide">
                  {strategy.title}
                </Badge>
                
                <h2 className="font-serif text-4xl md:text-5xl lg:text-6xl mb-6 leading-[1.1] tracking-tight">
                  {strategy.goal}
                </h2>
                
                <p className="text-gray-300 font-sans text-lg md:text-xl leading-relaxed max-w-lg mb-10 font-light">
                  High-impact visuals designed to increase product confidence and drive conversion across all channels.
                </p>

                <div className="flex gap-3 overflow-x-auto pb-4 -mx-4 px-4 md:flex-wrap md:overflow-visible md:pb-0 md:mx-0 md:px-0 scrollbar-hide snap-x">
                  {strategy.tone.split(',').map((tone) => (
                    <span 
                      key={tone} 
                      className="whitespace-nowrap px-5 py-2.5 rounded-full bg-white/5 border border-white/10 text-sm text-gray-200 backdrop-blur-md hover:bg-white/10 transition-colors cursor-default snap-start"
                    >
                      {tone.trim()}
                    </span>
                  ))}
                </div>
             </div>

             {/* Visual Texture Side */}
             <div className="relative w-full md:w-[45%] h-64 md:h-full min-h-[400px] overflow-hidden">
                <div className="absolute inset-0 bg-gradient-to-l from-transparent via-[#1E1E24]/50 to-[#1E1E24] z-10" />
                <img 
                  src="https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&q=80&w=2000" 
                  alt="Campaign Mood" 
                  className="absolute inset-0 w-full h-full object-cover opacity-80 mix-blend-overlay"
                />
                <div className="absolute top-1/2 right-0 -translate-y-1/2 w-[500px] h-[500px] bg-indigo-500/30 rounded-full blur-[120px] mix-blend-screen" />
                <div className="absolute bottom-0 right-20 w-[300px] h-[300px] bg-purple-500/20 rounded-full blur-[100px] mix-blend-screen" />
             </div>
          </div>
        </motion.div>

        {/* --- SECTION 2: CHANNELS (What Content Will Be Created) --- */}
        <motion.div variants={itemVariants} className="space-y-8">
          <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 px-2">
             <div>
                <h3 className="font-serif text-3xl text-[#111111] mb-2">Campaign Deliverables</h3>
                <p className="text-gray-500 text-lg">Optimized assets for your key growth channels.</p>
             </div>
             <div className="hidden md:flex items-center gap-2 text-sm text-gray-400">
               <Zap className="w-4 h-4" /> Auto-formatted for best performance
             </div>
          </div>
          
          <div className="flex gap-4 overflow-x-auto pb-6 -mx-4 px-4 snap-x scrollbar-hide md:grid md:grid-cols-2 lg:grid-cols-4 md:gap-6 md:mx-0 md:px-0 md:overflow-visible">
            {channelPacks.map((pack, i) => {
              const Icon = ChannelIcons[pack.channel] || Monitor;
              // Map technical names to human friendly ones
              const humanName = pack.channel === 'Shopify' ? 'Product Pages' : 
                                pack.channel === 'Instagram' ? 'Social Feeds' :
                                pack.channel === 'YouTube' ? 'Video Shorts' :
                                pack.channel;
                                
              return (
                <motion.div 
                  whileHover={{ y: -4 }}
                  key={i} 
                  className="min-w-[85vw] md:min-w-0 bg-white rounded-[24px] p-2 shadow-sm border border-gray-100 flex flex-col group h-full snap-center"
                >
                  {/* Visual Preview */}
                  <div className="relative aspect-[4/5] rounded-[20px] overflow-hidden mb-4 bg-gray-100">
                    <img 
                      src={`https://source.unsplash.com/random/600x800?fashion,${pack.channel.toLowerCase()}&sig=${i}`} 
                      alt="Channel Preview" 
                      className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
                    />
                    <div className="absolute top-3 right-3 bg-white/90 backdrop-blur-md px-2.5 py-1 rounded-full text-xs font-bold text-[#111111] shadow-sm">
                      {pack.outputCount} Assets
                    </div>
                  </div>

                  <div className="px-3 pb-4 flex-1 flex flex-col">
                    <div className="flex items-center gap-3 mb-2">
                       <div className="w-8 h-8 rounded-full bg-[#F8F5F1] flex items-center justify-center text-[#111111]">
                         <Icon className="w-4 h-4" />
                       </div>
                       <h4 className="font-serif text-lg text-[#111111]">{humanName}</h4>
                    </div>
                    
                    <p className="text-sm text-gray-500 leading-relaxed mb-4 flex-1">
                      {pack.rationale}
                    </p>

                    <div className="flex flex-wrap gap-2 pt-4 border-t border-gray-50">
                       {pack.usage.slice(0, 2).map(u => (
                         <span key={u} className="text-[10px] uppercase tracking-wider font-medium text-gray-400 border border-gray-100 px-2 py-1 rounded-md">
                           {u}
                         </span>
                       ))}
                    </div>

                    {isAdjustMode && (
                       <div className="flex items-center justify-between mt-4 bg-gray-50 p-1.5 rounded-full">
                         <button onClick={() => updatePackCount(i, false)} className="w-7 h-7 flex items-center justify-center bg-white rounded-full shadow-sm text-gray-600 hover:text-black">
                           <Minus className="w-3 h-3" />
                         </button>
                         <span className="text-xs font-bold">{pack.outputCount}</span>
                         <button onClick={() => updatePackCount(i, true)} className="w-7 h-7 flex items-center justify-center bg-white rounded-full shadow-sm text-gray-600 hover:text-black">
                           <Plus className="w-3 h-3" />
                         </button>
                       </div>
                    )}
                  </div>
                </motion.div>
              );
            })}
          </div>
        </motion.div>

        {/* --- SECTION 3: BRAND STORY & SOCIAL (The "Key Fix") --- */}
        <motion.div variants={itemVariants} className="space-y-8">
           <div className="px-2">
             <h3 className="font-serif text-3xl text-[#111111] mb-2">Visual Direction</h3>
             <p className="text-gray-500 text-lg max-w-2xl">
               A cinematic approach combining editorial polish with authentic social moments.
             </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 lg:gap-8">
             {/* Card 1: Lifestyle */}
             <div className="group relative aspect-[3/4] lg:aspect-[16/10] overflow-hidden rounded-[32px] bg-gray-900 shadow-xl">
                {renderSwapOverlay(1,
                  <ImageWithFallback 
                    src={assets[1]?.url || "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=1200"} 
                    alt="Lifestyle"
                    className="absolute inset-0 w-full h-full object-cover opacity-90 group-hover:scale-105 transition-transform duration-1000" 
                  />,
                  "absolute inset-0 w-full h-full"
                )}
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-black/20 to-transparent p-8 md:p-12 flex flex-col justify-end pointer-events-none">
                   <div className="space-y-4 transform translate-y-4 group-hover:translate-y-0 transition-transform duration-500">
                     <div className="bg-white text-[#111111] text-xs font-bold uppercase tracking-widest px-3 py-1.5 rounded w-fit">
                       Editorial
                     </div>
                     <div>
                       <h4 className="text-white font-serif text-3xl md:text-4xl mb-2">Lifestyle Photography</h4>
                       <p className="text-white/80 text-lg font-light max-w-md">
                         Rich, contextual imagery that situates the product in a world of aspiration and ease.
                       </p>
                     </div>
                   </div>
                </div>
             </div>

             {/* Card 2: Social */}
             <div className="group relative aspect-[3/4] lg:aspect-[16/10] overflow-hidden rounded-[32px] bg-gray-900 shadow-xl">
                {renderSwapOverlay(3,
                  <ImageWithFallback 
                    src={assets[3]?.url || "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=1200"} 
                    alt="Social"
                    className="absolute inset-0 w-full h-full object-cover opacity-90 group-hover:scale-105 transition-transform duration-1000" 
                  />,
                  "absolute inset-0 w-full h-full"
                )}
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-black/20 to-transparent p-8 md:p-12 flex flex-col justify-end pointer-events-none">
                   <div className="space-y-4 transform translate-y-4 group-hover:translate-y-0 transition-transform duration-500">
                     <div className="bg-white text-[#111111] text-xs font-bold uppercase tracking-widest px-3 py-1.5 rounded w-fit">
                       Authentic
                     </div>
                     <div>
                       <h4 className="text-white font-serif text-3xl md:text-4xl mb-2">Social Storytelling</h4>
                       <p className="text-white/80 text-lg font-light max-w-md">
                         Candid, motion-blur moments and BTS clips that build trust and community.
                       </p>
                     </div>
                   </div>
                </div>
             </div>
          </div>
        </motion.div>

        {/* --- SECTION 4: MESSAGING --- */}
        <motion.div variants={itemVariants} className="space-y-8">
          <div className="px-2">
             <h3 className="font-serif text-3xl text-[#111111]">Key Messages</h3>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-6">
             {ads.map((ad, i) => (
               <div 
                 key={ad.id} 
                 className="bg-white border border-gray-100 p-8 rounded-[24px] shadow-sm hover:shadow-lg transition-all relative overflow-hidden group"
               >
                 <div className="absolute top-0 right-0 w-32 h-32 bg-[#F8F5F1] rounded-bl-[100px] -mr-10 -mt-10 transition-transform group-hover:scale-110" />
                 
                 <div className="relative z-10">
                   <div className="flex justify-between items-center mb-6">
                     <span className="text-xs font-bold text-gray-400 uppercase tracking-widest flex items-center gap-2">
                       {ad.platform === 'Instagram' && <Instagram className="w-4 h-4" />}
                       {ad.platform === 'Facebook' && <Facebook className="w-4 h-4" />}
                       {ad.platform}
                     </span>
                     <span className={`text-[10px] font-bold uppercase tracking-wider px-3 py-1 rounded-full ${
                       ad.funnelStage === 'Awareness' ? 'bg-blue-50 text-blue-600' : 
                       ad.funnelStage === 'Conversion' ? 'bg-emerald-50 text-emerald-600' : 'bg-purple-50 text-purple-600'
                     }`}>
                       {ad.funnelStage}
                     </span>
                   </div>
                   
                   <h4 className="font-serif text-2xl md:text-3xl text-[#111111] mb-4 leading-tight">"{ad.hook}"</h4>
                   
                   <div className="flex items-center gap-4 pt-6 border-t border-gray-50">
                     <span className="text-xs font-medium text-gray-500 uppercase tracking-wide">CTA</span>
                     <div className="flex items-center gap-2 text-sm font-bold text-[#111111]">
                       {ad.cta} <ArrowRight className="w-4 h-4" />
                     </div>
                   </div>
                 </div>
               </div>
             ))}
          </div>
        </motion.div>

        {/* --- SECTION 5: IMPACT --- */}
        <motion.div variants={itemVariants} className="pb-12">
           <div className="bg-[#F8F5F1] rounded-[32px] p-8 md:p-12">
             <div className="flex flex-col md:flex-row md:items-center justify-between gap-8">
               <div className="flex-1">
                 <h3 className="font-serif text-2xl text-[#111111] mb-2">Predicted Impact</h3>
                 <p className="text-gray-500">Based on category benchmarks.</p>
               </div>
               
               <div className="flex gap-12">
                 <div className="space-y-1">
                   <div className="flex items-center gap-2 text-sm font-medium text-gray-500 uppercase tracking-wider">
                     <TrendingUp className="w-4 h-4" /> Conversion
                   </div>
                   <div className="text-4xl font-serif text-[#111111]">High</div>
                 </div>
                 <div className="space-y-1">
                   <div className="flex items-center gap-2 text-sm font-medium text-gray-500 uppercase tracking-wider">
                     <Globe className="w-4 h-4" /> Brand Lift
                   </div>
                   <div className="text-4xl font-serif text-[#111111]">Medium</div>
                 </div>
               </div>
             </div>
           </div>
        </motion.div>

      </motion.div>

      {/* --- STICKY FOOTER --- */}
      <div className="fixed bottom-0 left-0 w-full bg-white/90 backdrop-blur-xl border-t border-gray-100 p-4 md:p-6 z-50 shadow-[0_-4px_30px_rgba(0,0,0,0.05)]">
        <div className="max-w-[1600px] mx-auto flex flex-col md:flex-row gap-6 md:items-center justify-between">
          
          <div className="flex items-center gap-6">
             <div>
               <div className="text-xs text-gray-500 uppercase tracking-wider font-medium mb-1">Total Estimate</div>
               <div className="text-2xl font-serif text-[#111111] flex items-baseline gap-1">
                 ${pricing.total.toLocaleString()}
                 <span className="text-sm font-sans text-gray-400 font-normal">USD</span>
               </div>
             </div>
             <div className="hidden md:block h-10 w-px bg-gray-200" />
             <div className="hidden md:block">
                <div className="text-xs text-gray-500 uppercase tracking-wider font-medium mb-1">Deliverables</div>
                <div className="text-sm font-medium text-[#111111]">
                  {channelPacks.reduce((acc, p) => acc + p.outputCount, 0)} Assets included
                </div>
             </div>
          </div>

          <div className="flex items-center gap-4">
             <button 
               onClick={() => onNavigate('ai-optimization')}
               className="hidden md:flex items-center gap-2 px-6 py-3 rounded-xl text-sm font-medium text-indigo-600 hover:bg-indigo-50 transition-colors"
             >
               <Sparkles className="w-4 h-4" />
               Ask AI to Adjust
             </button>
             <Button 
               onClick={() => onNavigate('proposal-ready')}
               className="flex-1 md:flex-none bg-[#111111] hover:bg-black text-white rounded-[14px] px-8 py-6 h-auto text-base font-medium shadow-xl shadow-black/10 transition-transform active:scale-95"
             >
               Approve Proposal
               <ArrowRight className="w-4 h-4 ml-2" />
             </Button>
          </div>

        </div>
      </div>

      {/* --- SWAP ASSET SHEET --- */}
      <Sheet open={swappingAssetIndex !== null} onOpenChange={(open) => !open && setSwappingAssetIndex(null)}>
         <SheetContent side="bottom" className="h-[80vh] sm:h-auto rounded-t-[32px] p-0 border-0">
           <div className="p-8">
             <SheetHeader className="mb-8 text-left">
               <SheetTitle className="font-serif text-3xl text-[#111111]">Select Visual Direction</SheetTitle>
               <SheetDescription className="text-base text-gray-500">
                 Choose an alternative visual style. The AI will adapt the rest of the campaign to match.
               </SheetDescription>
             </SheetHeader>
             
             <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 gap-4 overflow-y-auto pb-8">
                {[1,2,3,4,5,6,7,8].map(i => {
                   const seed = (swappingAssetIndex || 0) * 10 + i;
                   const keyword = swappingAssetIndex === 0 ? "product,minimal,studio" : 
                                   swappingAssetIndex === 1 ? "lifestyle,fashion,editorial" : 
                                   swappingAssetIndex === 2 ? "texture,fabric,detail" : "social,style,street";
                   const url = `https://source.unsplash.com/random/600x800?${keyword}&sig=${seed}`;
                   
                   return (
                     <div 
                       key={i}
                       className="relative aspect-[3/4] rounded-2xl overflow-hidden cursor-pointer group"
                       onClick={() => handleAssetSwap(url)}
                     >
                       <ImageWithFallback 
                         src={url}
                         className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                         alt="Alternative option"
                       />
                       <div className="absolute inset-0 bg-black/0 group-hover:bg-black/20 transition-colors flex items-center justify-center">
                          <div className="bg-white text-gray-900 rounded-full p-3 opacity-0 group-hover:opacity-100 transform scale-90 group-hover:scale-100 transition-all shadow-xl">
                            <Check className="w-5 h-5" />
                          </div>
                       </div>
                     </div>
                   );
                })}
             </div>
           </div>
         </SheetContent>
      </Sheet>

    </div>
  );
}
