import React, { useState } from 'react';
import { 
  ArrowRight, Check, Sparkles, TrendingUp, Layers, 
  Instagram, ShoppingBag, Globe, Video, Camera, 
  Facebook, Youtube, Plus, Minus, Monitor, Share2
} from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { Button } from '../ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Badge } from '../ui/badge';
import { Separator } from '../ui/separator';
import { useBrandShoot } from '../../context/BrandShootContext';

// --- Icons Map ---
const ChannelIcons: Record<string, React.ElementType> = {
  Instagram: Instagram,
  Facebook: Facebook,
  YouTube: Youtube,
  TikTok: Share2, // Lucide doesn't have TikTok, using Share2 as proxy
  Pinterest: Layers,
  Shopify: ShoppingBag,
  Amazon: ShoppingBag,
  Website: Monitor
};

interface CampaignSummaryProps {
  onNavigate: (screen: string) => void;
}

export function CampaignSummary({ onNavigate }: CampaignSummaryProps) {
  const { 
    campaignPlan, 
    isAdjustMode, 
    setAdjustMode,
    updatePackCount
  } = useBrandShoot();

  if (!campaignPlan) {
    return <div className="min-h-screen flex items-center justify-center">Loading plan...</div>;
  }

  const { strategy, recipes, ads, roi, pricing, channelPacks, assets } = campaignPlan;

  // --- Animation Variants ---
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: { 
      opacity: 1,
      transition: { staggerChildren: 0.1 }
    }
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 }
  };

  return (
    <div className="min-h-screen bg-[#FDFBF9] pb-32 font-sans text-gray-900">
      
      {/* --- HEADER --- */}
      <div className="sticky top-0 z-40 bg-white/90 backdrop-blur-md border-b border-gray-100 px-4 py-4 md:px-6 flex items-center justify-between">
        <div>
          <h1 className="font-serif text-xl font-medium text-gray-900">Campaign Plan</h1>
          <div className="flex items-center gap-1 text-xs text-gray-500">
            <Sparkles className="w-3 h-3 text-indigo-500" />
            Generated by Gemini 3 Pro
          </div>
        </div>

        {/* Mode Toggle */}
        <div className="bg-gray-100 p-1 rounded-lg flex items-center">
          <button
            onClick={() => setAdjustMode(false)}
            className={`px-3 py-1.5 rounded-md text-xs font-medium transition-all ${
              !isAdjustMode 
                ? 'bg-white text-gray-900 shadow-sm' 
                : 'text-gray-500 hover:text-gray-900'
            }`}
          >
            AI Recommended
          </button>
          <button
            onClick={() => setAdjustMode(true)}
            className={`px-3 py-1.5 rounded-md text-xs font-medium transition-all ${
              isAdjustMode 
                ? 'bg-white text-gray-900 shadow-sm' 
                : 'text-gray-500 hover:text-gray-900'
            }`}
          >
            Adjust Mode
          </button>
        </div>
      </div>

      <motion.div 
        variants={containerVariants}
        initial="hidden"
        animate="visible"
        className="max-w-2xl mx-auto px-4 md:px-6 pt-6 space-y-8"
      >

        {/* --- SECTION 1: STRATEGY HERO --- */}
        <motion.div variants={itemVariants}>
          <Card className="border-0 shadow-lg shadow-black/5 overflow-hidden">
            <div className="bg-gray-900 p-6 text-white relative overflow-hidden">
               <div className="relative z-10">
                  <Badge className="bg-white/20 hover:bg-white/30 text-white border-0 mb-3 backdrop-blur-sm">
                    {strategy.title}
                  </Badge>
                  <h2 className="font-serif text-3xl mb-2">{strategy.goal}</h2>
                  <div className="flex flex-wrap gap-2 text-sm text-gray-300">
                    <span className="bg-white/10 px-2 py-1 rounded">{strategy.tone}</span>
                  </div>
               </div>
               {/* Abstract BG */}
               <div className="absolute -right-10 -bottom-20 w-64 h-64 bg-indigo-500/30 rounded-full blur-3xl" />
            </div>
            
            <div className="p-4 flex flex-wrap gap-2 bg-white">
              {strategy.channels.map(channel => (
                <Badge key={channel} variant="secondary" className="bg-gray-100 text-gray-600 font-normal">
                  {channel}
                </Badge>
              ))}
            </div>
          </Card>
        </motion.div>

        {/* --- SECTION 2: CHANNEL OUTPUT PACKS --- */}
        <motion.div variants={itemVariants} className="space-y-4">
          <h3 className="font-serif text-lg text-gray-900 px-1">Channel Output Packs</h3>
          
          {/* Horizontal Scroll Container */}
          <div className="flex gap-4 overflow-x-auto pb-4 -mx-4 px-4 snap-x hide-scrollbar">
            {channelPacks.map((pack, i) => {
              const Icon = ChannelIcons[pack.channel] || Monitor;
              return (
                <div key={i} className="min-w-[280px] bg-white rounded-xl p-5 shadow-sm border border-gray-100 snap-center flex flex-col justify-between">
                  <div>
                    <div className="flex justify-between items-start mb-4">
                      <div className="flex items-center gap-2">
                        <div className="p-2 bg-gray-50 rounded-lg">
                          <Icon className="w-5 h-5 text-gray-900" />
                        </div>
                        <span className="font-medium text-gray-900">{pack.channel}</span>
                      </div>
                      <Badge variant="outline" className="text-gray-500 text-xs">
                        {pack.outputCount} Assets
                      </Badge>
                    </div>
                    
                    <div className="space-y-3 mb-4">
                      <div className="flex flex-wrap gap-1">
                        {pack.formats.map(fmt => (
                          <span key={fmt} className="text-[10px] uppercase tracking-wider bg-gray-50 px-2 py-1 rounded text-gray-500">
                            {fmt}
                          </span>
                        ))}
                      </div>
                      <p className="text-xs text-gray-500 leading-relaxed italic border-l-2 border-gray-200 pl-3">
                        "{pack.rationale}"
                      </p>
                    </div>
                  </div>

                  <div className="flex gap-2 mt-2">
                     {pack.usage.map(u => (
                       <Badge key={u} className={`text-[10px] ${
                         u === 'Paid' ? 'bg-indigo-50 text-indigo-700 hover:bg-indigo-100' :
                         u === 'PDP' ? 'bg-amber-50 text-amber-700 hover:bg-amber-100' :
                         'bg-green-50 text-green-700 hover:bg-green-100'
                       } border-0`}>
                         {u}
                       </Badge>
                     ))}
                  </div>

                  {isAdjustMode && (
                     <div className="mt-4 pt-3 border-t border-gray-100 flex items-center justify-between animate-in fade-in">
                       <span className="text-xs font-medium text-gray-500">Adjust Qty</span>
                       <div className="flex items-center gap-3">
                         <button 
                           onClick={() => updatePackCount(i, false)}
                           className="w-6 h-6 rounded-full bg-gray-100 flex items-center justify-center hover:bg-gray-200"
                         >
                           <Minus className="w-3 h-3" />
                         </button>
                         <span className="text-sm font-medium w-4 text-center">{pack.outputCount}</span>
                         <button 
                           onClick={() => updatePackCount(i, true)}
                           className="w-6 h-6 rounded-full bg-gray-100 flex items-center justify-center hover:bg-gray-200"
                         >
                           <Plus className="w-3 h-3" />
                         </button>
                       </div>
                     </div>
                  )}
                </div>
              );
            })}
          </div>
        </motion.div>

        {/* --- SECTION 3: EXTRACTED BRAND ASSETS --- */}
        <motion.div variants={itemVariants} className="space-y-4">
           <h3 className="font-serif text-lg text-gray-900 px-1">Extracted Brand DNA</h3>
           <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
             {assets.map((asset, i) => (
               <div key={i} className="aspect-[4/5] rounded-xl relative overflow-hidden group bg-gray-100">
                 <img src={asset.url} alt="Brand Asset" className="w-full h-full object-cover" />
                 <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex flex-col justify-end p-2">
                   <span className="text-[10px] text-white/80 uppercase tracking-wider">{asset.source}</span>
                   <span className="text-xs text-white font-medium">{asset.usage}</span>
                 </div>
                 {/* Confidence Chip */}
                 <div className="absolute top-2 right-2 bg-white/90 backdrop-blur text-[10px] px-1.5 py-0.5 rounded text-green-700 font-medium">
                   98% Match
                 </div>
               </div>
             ))}
           </div>
        </motion.div>

        {/* --- SECTION 4: AI ASSET RECIPES --- */}
        <motion.div variants={itemVariants} className="space-y-4">
          <h3 className="font-serif text-lg text-gray-900 px-1">Asset Recipes</h3>
          <div className="space-y-3">
            {recipes.map((recipe) => (
              <Card key={recipe.id} className="border border-gray-100 shadow-sm">
                <CardContent className="p-5">
                   <div className="flex justify-between items-start mb-3">
                     <h4 className="font-medium text-gray-900">{recipe.title}</h4>
                     <Badge variant="outline" className="text-indigo-600 bg-indigo-50 border-indigo-100">
                       {recipe.confidence}% Confidence
                     </Badge>
                   </div>
                   
                   <p className="text-sm text-gray-500 mb-4">{recipe.rationale}</p>
                   
                   <div className="flex flex-wrap gap-2 mb-4">
                     {recipe.requirements.map(req => (
                       <span key={req} className="text-xs bg-gray-50 text-gray-600 px-2 py-1 rounded border border-gray-100">
                         {req}
                       </span>
                     ))}
                   </div>
                   
                   <Separator className="my-3" />
                   
                   <div className="flex gap-4 overflow-x-auto pb-1">
                     {Object.entries(recipe.outputs).map(([channel, qty]) => (
                       <div key={channel} className="flex flex-col items-center min-w-[60px]">
                         <span className="text-[10px] uppercase text-gray-400 mb-1">{channel}</span>
                         <span className="text-sm font-medium text-gray-900 bg-gray-50 w-full text-center py-1 rounded">
                           x{qty}
                         </span>
                       </div>
                     ))}
                   </div>

                   {isAdjustMode && (
                     <div className="mt-4 pt-3 border-t border-gray-100 animate-in fade-in">
                        <Button variant="ghost" size="sm" className="w-full text-indigo-600 hover:text-indigo-700 hover:bg-indigo-50 h-8 text-xs">
                          Customize Recipe Details
                        </Button>
                     </div>
                   )}
                </CardContent>
              </Card>
            ))}
          </div>
        </motion.div>

        {/* --- SECTION 5: ADS CREATIVE --- */}
        <motion.div variants={itemVariants} className="space-y-4">
          <div className="flex items-center gap-2 px-1">
             <h3 className="font-serif text-lg text-gray-900">Ads Creative</h3>
             <Badge className="bg-purple-100 text-purple-700 hover:bg-purple-200 border-0 text-[10px]">New</Badge>
          </div>
          
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
             {ads.map((ad) => (
               <div key={ad.id} className="bg-gradient-to-br from-gray-50 to-white border border-gray-200 p-4 rounded-xl relative overflow-hidden">
                 <div className="absolute top-0 right-0 w-16 h-16 bg-purple-500/5 rounded-bl-full" />
                 
                 <div className="relative z-10">
                   <div className="flex justify-between items-start mb-2">
                     <span className="text-xs font-bold text-gray-400 uppercase tracking-wider">{ad.platform}</span>
                     <Badge variant="secondary" className="text-[10px] bg-white border border-gray-100">{ad.funnelStage}</Badge>
                   </div>
                   
                   <h4 className="font-medium text-gray-900 mb-1">{ad.hook}</h4>
                   <p className="text-xs text-gray-500 mb-3">{ad.format}</p>
                   
                   <div className="inline-flex items-center gap-1.5 bg-gray-900 text-white text-xs px-3 py-1.5 rounded-full">
                     <span>CTA: {ad.cta}</span>
                   </div>
                 </div>
               </div>
             ))}
          </div>
        </motion.div>

        {/* --- SECTION 7: ROI --- */}
        <motion.div variants={itemVariants} className="space-y-4 pb-8">
           <h3 className="font-serif text-lg text-gray-900 px-1">Predicted Impact</h3>
           <div className="grid grid-cols-2 gap-4">
             <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm">
               <div className="flex items-center gap-2 mb-2">
                 <TrendingUp className="w-4 h-4 text-green-600" />
                 <span className="text-sm font-medium text-gray-900">Conversion</span>
               </div>
               <div className="text-2xl font-serif text-gray-900 mb-1">High</div>
               <div className="text-[10px] text-gray-500">Above category standard</div>
             </div>
             <div className="bg-white p-4 rounded-xl border border-gray-100 shadow-sm">
               <div className="flex items-center gap-2 mb-2">
                 <Globe className="w-4 h-4 text-blue-600" />
                 <span className="text-sm font-medium text-gray-900">Brand Lift</span>
               </div>
               <div className="text-2xl font-serif text-gray-900 mb-1">Medium</div>
               <div className="text-[10px] text-gray-500">Typical for editorial</div>
             </div>
           </div>
        </motion.div>

      </motion.div>

      {/* --- STICKY CTA --- */}
      <div className="fixed bottom-0 left-0 w-full bg-white border-t border-gray-100 p-4 pb-8 z-50 shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.05)]">
        <div className="max-w-2xl mx-auto flex flex-col gap-4">
          <div className="flex items-center gap-4">
            <div className="flex-1">
               <div className="flex items-baseline gap-2">
                 <span className="text-lg font-bold text-gray-900 animate-in fade-in duration-300 key={pricing.total}">${pricing.total.toLocaleString()}</span>
                 <span className="text-xs text-gray-500">Est. Total</span>
               </div>
               <div className="text-xs text-gray-400">Includes {channelPacks.reduce((acc, p) => acc + p.outputCount, 0)} Assets</div>
            </div>
            <Button 
              onClick={() => onNavigate('proposal-confirmation')}
              className="bg-gray-900 text-white hover:bg-black rounded-xl px-8 py-6 h-auto text-sm font-medium shadow-xl shadow-gray-900/20 transition-transform active:scale-95"
            >
              Approve Proposal
              <ArrowRight className="w-4 h-4 ml-2" />
            </Button>
          </div>
          
          {/* Secondary Actions */}
          <div className="flex items-center justify-between pt-2 border-t border-gray-50">
            <button className="text-xs text-gray-500 hover:text-gray-900 font-medium flex items-center gap-1">
              <span className="w-1.5 h-1.5 rounded-full bg-gray-300" />
              Download PDF
            </button>
            <button className="text-xs text-indigo-600 hover:text-indigo-700 font-medium flex items-center gap-1">
              <Sparkles className="w-3 h-3" />
              Ask AI to Adjust
            </button>
          </div>
        </div>
      </div>

    </div>
  );
}
