import { useState, useEffect } from "react";
import { motion } from "motion/react";
import { 
  CheckCircle2, 
  Download, 
  ArrowRight, 
  Calendar, 
  FileText, 
  ShieldCheck,
  Sparkles
} from "lucide-react";

export function ProposalPreview({ onNavigate, proposalData }: { onNavigate: (screen: string) => void, proposalData?: any }) {
  const [isGenerating, setIsGenerating] = useState(true);

  // Derive dynamic content from proposalData
  const serviceTitle = proposalData?.service ? `${proposalData.service.charAt(0).toUpperCase() + proposalData.service.slice(1)} Production` : "Production Campaign";
  const category = proposalData?.category ? proposalData.category.charAt(0).toUpperCase() + proposalData.category.slice(1) : "Fashion";
  const totalCost = 1500 + (proposalData?.addOns?.length || 0) * 300; // Simplified calculation
  
  useEffect(() => {
    // Simulate AI Generation delay
    const timer = setTimeout(() => {
      setIsGenerating(false);
    }, 2500);
    return () => clearTimeout(timer);
  }, []);

  if (isGenerating) {
    return (
      <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-6">
        <motion.div 
          animate={{ rotate: 360 }}
          transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
          className="w-16 h-16 border-4 border-gray-200 border-t-gray-900 rounded-full mb-8"
        />
        <h2 className="text-2xl font-serif text-gray-900 mb-2">Generating Proposal</h2>
        <div className="flex flex-col gap-2 items-center text-sm text-gray-500 font-mono">
          <Typewriter text={`Analyzing ${serviceTitle.toLowerCase()} requirements...`} delay={0} />
          <Typewriter text={`Tailoring for ${category} category...`} delay={1000} />
          <Typewriter text="Checking studio availability..." delay={2000} />
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#F8F9FA] pb-24">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 sticky top-0 z-20">
        <div className="max-w-5xl mx-auto px-6 h-20 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 bg-gray-900 text-white flex items-center justify-center rounded-lg">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h1 className="font-serif font-bold text-lg text-gray-900">Project Proposal</h1>
              <p className="text-xs text-gray-500 font-mono">REF: PR-2025-{Math.floor(Math.random() * 1000)} • GENERATED BY FASHIONOS AI</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button className="hidden md:flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-600 hover:text-gray-900 border border-gray-200 rounded-lg transition-colors">
              <Download className="w-4 h-4" /> Export PDF
            </button>
            <button 
              onClick={() => onNavigate('booking')}
              className="flex items-center gap-2 px-6 py-2 text-sm font-medium text-white bg-gray-900 hover:bg-black rounded-lg transition-colors shadow-lg shadow-gray-900/20"
            >
              Secure Slot <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

      <div className="max-w-5xl mx-auto px-6 py-12">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="grid lg:grid-cols-3 gap-8"
        >
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-8">
            
            {/* Executive Summary */}
            <section className="bg-white rounded-2xl p-8 border border-gray-100 shadow-sm">
              <div className="flex items-center gap-2 mb-6">
                <Sparkles className="w-4 h-4 text-purple-500" />
                <h2 className="text-sm font-bold uppercase tracking-widest text-gray-900">Executive Summary</h2>
              </div>
              <p className="text-gray-600 leading-relaxed font-light text-lg">
                Based on your creative brief for a <span className="font-medium text-gray-900">{serviceTitle}</span>, we have outlined a production plan tailored to the <span className="font-medium text-gray-900">{category}</span> market. 
                This package includes studio access, a dedicated creative team, and post-production. 
                The objective is to deliver high-fidelity assets optimized for your selected channels.
              </p>
            </section>

            {/* Scope of Work */}
            <section className="bg-white rounded-2xl overflow-hidden border border-gray-100 shadow-sm">
              <div className="px-8 py-6 border-b border-gray-100 bg-gray-50/50">
                <h2 className="text-sm font-bold uppercase tracking-widest text-gray-900">Scope of Work</h2>
              </div>
              <div className="divide-y divide-gray-100">
                <ScopeItem 
                  title={`${serviceTitle}`} 
                  desc="Full Day Studio Access • Professional Equipment • Creative Direction" 
                />
                {proposalData?.scenes?.length > 0 && (
                   <ScopeItem 
                     title="Scene Setup" 
                     desc={`Custom set design for: ${proposalData.scenes.map((s: string) => s.charAt(0).toUpperCase() + s.slice(1)).join(", ")}`} 
                   />
                )}
                {proposalData?.addOns?.length > 0 ? (
                  <ScopeItem 
                    title="Additional Services" 
                    desc={`Includes: ${proposalData.addOns.join(", ")}`} 
                  />
                ) : (
                  <ScopeItem 
                    title="Standard Team" 
                    desc="1 Photographer • 1 Assistant" 
                  />
                )}
                <ScopeItem 
                  title="Post-Production" 
                  desc="Color Correction • Retouching • 48hr Turnaround" 
                />
              </div>
            </section>

            {/* Timeline */}
            <section className="bg-white rounded-2xl p-8 border border-gray-100 shadow-sm">
               <div className="flex items-center gap-2 mb-8">
                <Calendar className="w-4 h-4 text-gray-400" />
                <h2 className="text-sm font-bold uppercase tracking-widest text-gray-900">Estimated Timeline</h2>
              </div>
              <div className="relative pl-8 space-y-8 border-l border-gray-200">
                <TimelineItem 
                  date="Day 1" 
                  title="Pre-Production" 
                  desc="Moodboard finalization, casting confirmation, and wardrobe prep."
                />
                <TimelineItem 
                  date={proposalData?.date ? new Date(proposalData.date).toLocaleDateString() : "TBD"}
                  title="Production Day" 
                  desc={`Full team on set. ${proposalData?.timeSlot || "9:00 AM"}.`}
                  active
                />
                <TimelineItem 
                  date="Day +2" 
                  title="Post-Production Review" 
                  desc="First look at retouched assets via FashionOS Gallery."
                />
                <TimelineItem 
                  date="Day +4" 
                  title="Final Delivery" 
                  desc="High-res assets delivered to Digital Asset Management."
                />
              </div>
            </section>
          </div>

          {/* Sidebar - Cost & Terms */}
          <div className="space-y-6">
            <div className="bg-gray-900 text-white rounded-2xl p-8 shadow-xl">
              <h3 className="text-sm font-medium text-gray-400 uppercase tracking-wider mb-6">Total Estimate</h3>
              <div className="flex items-baseline gap-1 mb-2">
                <span className="text-4xl font-serif font-medium">${totalCost.toLocaleString()}</span>
                <span className="text-gray-400">.00</span>
              </div>
              <p className="text-sm text-gray-400 mb-8">Includes all taxes and fees</p>
              
              <div className="space-y-4 pt-6 border-t border-gray-800 mb-8">
                <div className="flex justify-between text-sm">
                  <span className="text-gray-400">Base Package</span>
                  <span>$1,500</span>
                </div>
                {proposalData?.addOns?.length > 0 && (
                   <div className="flex justify-between text-sm">
                     <span className="text-gray-400">Add-Ons</span>
                     <span>+${(proposalData.addOns.length * 300).toLocaleString()}</span>
                   </div>
                )}
                <div className="flex justify-between text-sm">
                  <span className="text-gray-400">Platform Fee</span>
                  <span>Included</span>
                </div>
              </div>

              <button 
                onClick={() => onNavigate('booking')}
                className="w-full py-4 bg-white text-gray-900 rounded-xl font-bold hover:bg-gray-100 transition-colors flex items-center justify-center gap-2"
              >
                Proceed to Booking <ArrowRight className="w-4 h-4" />
              </button>
            </div>

            <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
              <h3 className="text-sm font-bold text-gray-900 mb-4 flex items-center gap-2">
                <ShieldCheck className="w-4 h-4 text-green-600" /> FashionOS Guarantee
              </h3>
              <ul className="space-y-3">
                <li className="text-sm text-gray-600 flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-gray-400 mt-0.5 shrink-0" />
                  <span>Vetted industry professionals</span>
                </li>
                <li className="text-sm text-gray-600 flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-gray-400 mt-0.5 shrink-0" />
                  <span>Secure asset storage</span>
                </li>
                <li className="text-sm text-gray-600 flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-gray-400 mt-0.5 shrink-0" />
                  <span>Satisfaction guarantee on retouching</span>
                </li>
              </ul>
            </div>
          </div>

        </motion.div>
      </div>
    </div>
  );
}

function ScopeItem({ title, desc }: { title: string, desc: string }) {
  return (
    <div className="px-8 py-6 flex flex-col md:flex-row md:items-center justify-between gap-4 group hover:bg-gray-50 transition-colors">
      <div>
        <h3 className="font-serif font-medium text-gray-900">{title}</h3>
        <p className="text-sm text-gray-500 mt-1">{desc}</p>
      </div>
      <div className="w-6 h-6 rounded-full border border-gray-200 flex items-center justify-center group-hover:border-gray-900 group-hover:bg-gray-900 transition-all">
        <CheckCircle2 className="w-4 h-4 text-white opacity-0 group-hover:opacity-100" />
      </div>
    </div>
  );
}

function TimelineItem({ date, title, desc, active = false }: { date: string, title: string, desc: string, active?: boolean }) {
  return (
    <div className="relative">
      <div className={`
        absolute -left-[39px] w-5 h-5 rounded-full border-2 
        ${active ? 'bg-gray-900 border-gray-900' : 'bg-white border-gray-300'}
      `} />
      <span className="text-xs font-bold text-gray-400 uppercase tracking-wider block mb-1">{date}</span>
      <h3 className="font-serif font-medium text-gray-900">{title}</h3>
      <p className="text-sm text-gray-500 mt-1">{desc}</p>
    </div>
  );
}

function Typewriter({ text, delay }: { text: string, delay: number }) {
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const timer = setTimeout(() => setVisible(true), delay);
    return () => clearTimeout(timer);
  }, [delay]);

  if (!visible) return null;
  return (
    <motion.span 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="block"
    >
      {text}
    </motion.span>
  );
}
