import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import { 
  CheckCircle2, 
  Download, 
  ArrowRight, 
  Calendar, 
  FileText, 
  ShieldCheck,
  Sparkles,
  RefreshCw,
  PlusCircle,
  XCircle
} from "lucide-react";
import { Button } from "../ui/button";

import { BudgetWatchdog } from "./BudgetWatchdog";
import { useBrandShoot } from "../../context/BrandShootContext";

export function ProposalPreview({ onNavigate, proposalData }: { onNavigate: (screen: string) => void, proposalData?: any }) {
  const { setProposal } = useBrandShoot();
  const [isGenerating, setIsGenerating] = useState(true);
  
  // Local state to manage active add-ons, defaulting to what's passed in proposalData
  const [activeAddOns, setActiveAddOns] = useState<string[]>([]);
  
  useEffect(() => {
    if (proposalData?.addOns) {
      setActiveAddOns(proposalData.addOns);
    }
  }, [proposalData]);

  // Derive dynamic content
  const serviceTitle = proposalData?.service ? `${proposalData.service.charAt(0).toUpperCase() + proposalData.service.slice(1)} Production` : "Production Campaign";
  const category = proposalData?.category ? proposalData.category.charAt(0).toUpperCase() + proposalData.category.slice(1) : "Fashion";
  
  // Simplified calculation based on local state
  const basePrice = 1500;
  const addOnPrice = 300;
  const totalCost = basePrice + (activeAddOns.length * addOnPrice);

  // Sync with global context whenever important data changes
  useEffect(() => {
    if (!isGenerating && proposalData) {
      setProposal({
        service: proposalData.service || "Production",
        category: proposalData.category || "Fashion",
        date: proposalData.date,
        timeSlot: proposalData.timeSlot,
        scenes: proposalData.scenes || [],
        activeAddOns: activeAddOns,
        totalCost: totalCost
      });
    }
  }, [activeAddOns, totalCost, isGenerating, proposalData, setProposal]);
  
  const handleRemoveAddOn = (addOn: string) => {
    setActiveAddOns(prev => prev.filter(a => a !== addOn));
  };

  const handleApplySavings = () => {
    if (activeAddOns.length > 0) {
      // Remove the last add-on as a simulation of "smart optimization"
      const newAddOns = [...activeAddOns];
      newAddOns.pop();
      setActiveAddOns(newAddOns);
    }
  };
  
  useEffect(() => {
    // Simulate AI Generation delay
    const timer = setTimeout(() => {
      setIsGenerating(false);
    }, 2500);
    return () => clearTimeout(timer);
  }, []);

  if (isGenerating) {
    return (
      <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-6">
        <motion.div 
          animate={{ rotate: 360 }}
          transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
          className="w-16 h-16 border-4 border-gray-200 border-t-gray-900 rounded-full mb-8"
        />
        <h2 className="text-2xl font-serif text-gray-900 mb-2">Generating Proposal</h2>
        <div className="flex flex-col gap-2 items-center text-sm text-gray-500 font-mono">
          <Typewriter text={`Analyzing ${serviceTitle.toLowerCase()} requirements...`} delay={0} />
          <Typewriter text={`Tailoring for ${category} category...`} delay={1000} />
          <Typewriter text="Checking studio availability..." delay={2000} />
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#FAFAFA] pb-24 font-sans text-[#111111] overflow-x-hidden selection:bg-indigo-100 selection:text-indigo-900">
      {/* Header */}
      <div className="sticky top-0 z-30 bg-white/80 backdrop-blur-xl border-b border-gray-100/50">
        <div className="max-w-[1600px] mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <div className="w-10 h-10 bg-[#111111] text-white flex items-center justify-center rounded-xl shadow-lg shadow-black/10">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h1 className="font-serif font-medium text-lg text-[#111111]">Project Proposal</h1>
              <p className="text-xs text-gray-500 font-medium">REF: PR-2025-{Math.floor(Math.random() * 1000)} • GENERATED BY CURA AI</p>
            </div>
          </div>
          <div className="flex items-center gap-3">
            <button className="hidden md:flex items-center gap-2 px-4 py-2 text-xs font-bold text-gray-600 hover:text-[#111111] border border-gray-200 rounded-xl hover:bg-gray-50 transition-colors">
              <Download className="w-4 h-4" /> Export PDF
            </button>
            <button 
              onClick={() => onNavigate('booking')}
              className="flex items-center gap-2 px-6 py-2 text-xs font-bold text-white bg-[#111111] hover:bg-black rounded-xl transition-colors shadow-lg shadow-black/20"
            >
              Secure Slot <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>

      <div className="max-w-[1600px] mx-auto px-6 md:px-8 py-12">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="grid lg:grid-cols-3 gap-8"
        >
          {/* Main Content */}
          <div className="lg:col-span-2 space-y-8">
            
            {/* Executive Summary */}
            <section className="bg-white rounded-2xl p-8 border border-gray-100 shadow-sm">
              <div className="flex items-center gap-2 mb-6">
                <Sparkles className="w-4 h-4 text-purple-500" />
                <h2 className="text-sm font-bold uppercase tracking-widest text-gray-900">Executive Summary</h2>
              </div>
              <p className="text-gray-600 leading-relaxed font-light text-lg">
                Based on your creative brief for a <span className="font-medium text-gray-900">{serviceTitle}</span>, we have outlined a production plan tailored to the <span className="font-medium text-gray-900">{category}</span> market. 
                This package includes studio access, a dedicated creative team, and post-production. 
                The objective is to deliver high-fidelity assets optimized for your selected channels.
              </p>
            </section>

            {/* Scope of Work */}
            <section className="bg-white rounded-2xl overflow-hidden border border-gray-100 shadow-sm">
              <div className="px-8 py-6 border-b border-gray-100 bg-gray-50/50 flex justify-between items-center">
                <h2 className="text-sm font-bold uppercase tracking-widest text-gray-900">Scope of Work</h2>
                <div className="text-xs font-medium text-gray-400">Customizable</div>
              </div>
              <div className="divide-y divide-gray-100">
                <ScopeItem 
                  title={`${serviceTitle}`} 
                  desc="Full Day Studio Access • Professional Equipment • Creative Direction" 
                  locked
                />
                {proposalData?.scenes?.length > 0 && (
                   <ScopeItem 
                     title="Scene Setup" 
                     desc={`Custom set design for: ${proposalData.scenes.map((s: string) => s.charAt(0).toUpperCase() + s.slice(1)).join(", ")}`} 
                     locked
                   />
                )}
                
                {/* Dynamic Add-Ons List */}
                <AnimatePresence>
                  {activeAddOns.map((addon) => (
                    <motion.div
                      key={addon}
                      initial={{ opacity: 0, height: 0 }}
                      animate={{ opacity: 1, height: 'auto' }}
                      exit={{ opacity: 0, height: 0 }}
                    >
                      <ScopeItem 
                        title={addon} 
                        desc="Optional add-on service included in proposal." 
                        onRemove={() => handleRemoveAddOn(addon)}
                        price={addOnPrice}
                      />
                    </motion.div>
                  ))}
                </AnimatePresence>
                
                {/* Fallback if no add-ons but default package */}
                {activeAddOns.length === 0 && (
                   <ScopeItem 
                     title="Standard Team" 
                     desc="1 Photographer • 1 Assistant" 
                     locked
                   />
                )}
                
                <ScopeItem 
                  title="Post-Production" 
                  desc="Color Correction • Retouching • 48hr Turnaround" 
                  locked
                />
              </div>
            </section>

            {/* Timeline */}
            <section className="bg-white rounded-2xl p-8 border border-gray-100 shadow-sm">
               <div className="flex items-center gap-2 mb-8">
                <Calendar className="w-4 h-4 text-gray-400" />
                <h2 className="text-sm font-bold uppercase tracking-widest text-gray-900">Estimated Timeline</h2>
              </div>
              <div className="relative pl-8 space-y-8 border-l border-gray-200">
                <TimelineItem 
                  date="Day 1" 
                  title="Pre-Production" 
                  desc="Moodboard finalization, casting confirmation, and wardrobe prep."
                />
                <TimelineItem 
                  date={proposalData?.date ? new Date(proposalData.date).toLocaleDateString() : "TBD"}
                  title="Production Day" 
                  desc={`Full team on set. ${proposalData?.timeSlot || "9:00 AM"}.`}
                  active
                />
                <TimelineItem 
                  date="Day +2" 
                  title="Post-Production Review" 
                  desc="First look at retouched assets via FashionOS Gallery."
                />
                <TimelineItem 
                  date="Day +4" 
                  title="Final Delivery" 
                  desc="High-res assets delivered to Digital Asset Management."
                />
              </div>
            </section>
          </div>

          {/* Sidebar - Cost & Terms */}
          <div className="space-y-6">
            
            {/* Budget Watchdog */}
            <BudgetWatchdog 
              currentTotal={totalCost} 
              budgetTarget={2000} 
              onAdjustScope={handleApplySavings} 
            />

            <div className="bg-gray-900 text-white rounded-2xl p-8 shadow-xl relative overflow-hidden">
               {/* Background Texture */}
               <div className="absolute top-0 right-0 w-32 h-32 bg-white opacity-5 rounded-full -mr-16 -mt-16 blur-2xl pointer-events-none" />

              <h3 className="text-sm font-medium text-gray-400 uppercase tracking-wider mb-6">Total Estimate</h3>
              
              <div className="flex items-baseline gap-1 mb-2">
                <AnimatePresence mode="wait">
                  <motion.span 
                    key={totalCost}
                    initial={{ opacity: 0, y: -10 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: 10 }}
                    className="text-4xl font-serif font-medium"
                  >
                    ${totalCost.toLocaleString()}
                  </motion.span>
                </AnimatePresence>
                <span className="text-gray-400">.00</span>
              </div>
              <p className="text-sm text-gray-400 mb-8">Includes all taxes and fees</p>
              
              <div className="space-y-4 pt-6 border-t border-gray-800 mb-8">
                <div className="flex justify-between text-sm">
                  <span className="text-gray-400">Base Package</span>
                  <span>${basePrice.toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-sm">
                   <span className="text-gray-400">Add-Ons ({activeAddOns.length})</span>
                   <span>+${(activeAddOns.length * addOnPrice).toLocaleString()}</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-gray-400">Platform Fee</span>
                  <span>Included</span>
                </div>
              </div>

              <button 
                onClick={() => onNavigate('booking')}
                className="w-full py-4 bg-white text-gray-900 rounded-xl font-bold hover:bg-gray-100 transition-colors flex items-center justify-center gap-2"
              >
                Proceed to Booking <ArrowRight className="w-4 h-4" />
              </button>
            </div>

            <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
              <h3 className="text-sm font-bold text-gray-900 mb-4 flex items-center gap-2">
                <ShieldCheck className="w-4 h-4 text-green-600" /> FashionOS Guarantee
              </h3>
              <ul className="space-y-3">
                <li className="text-sm text-gray-600 flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-gray-400 mt-0.5 shrink-0" />
                  <span>Vetted industry professionals</span>
                </li>
                <li className="text-sm text-gray-600 flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-gray-400 mt-0.5 shrink-0" />
                  <span>Secure asset storage</span>
                </li>
                <li className="text-sm text-gray-600 flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-gray-400 mt-0.5 shrink-0" />
                  <span>Satisfaction guarantee on retouching</span>
                </li>
              </ul>
            </div>
          </div>

        </motion.div>
      </div>
    </div>
  );
}

function ScopeItem({ title, desc, locked = false, onRemove, price }: { title: string, desc: string, locked?: boolean, onRemove?: () => void, price?: number }) {
  return (
    <div className="px-8 py-6 flex flex-col md:flex-row md:items-center justify-between gap-4 group hover:bg-gray-50 transition-colors">
      <div className="flex-1">
        <h3 className="font-serif font-medium text-gray-900 flex items-center gap-2">
          {title}
          {price && <span className="text-xs bg-gray-100 text-gray-500 px-2 py-0.5 rounded-full font-sans">+${price}</span>}
        </h3>
        <p className="text-sm text-gray-500 mt-1">{desc}</p>
      </div>
      
      {locked ? (
         <div className="w-8 h-8 flex items-center justify-center text-gray-300">
           <CheckCircle2 className="w-5 h-5 text-gray-300" />
         </div>
      ) : (
         <Button 
           variant="ghost" 
           size="icon" 
           onClick={onRemove}
           className="w-8 h-8 rounded-full text-gray-400 hover:text-red-500 hover:bg-red-50"
         >
            <XCircle className="w-5 h-5" />
         </Button>
      )}
    </div>
  );
}

function TimelineItem({ date, title, desc, active = false }: { date: string, title: string, desc: string, active?: boolean }) {
  return (
    <div className="relative">
      <div className={`
        absolute -left-[39px] w-5 h-5 rounded-full border-2 
        ${active ? 'bg-gray-900 border-gray-900' : 'bg-white border-gray-300'}
      `} />
      <span className="text-xs font-bold text-gray-400 uppercase tracking-wider block mb-1">{date}</span>
      <h3 className="font-serif font-medium text-gray-900">{title}</h3>
      <p className="text-sm text-gray-500 mt-1">{desc}</p>
    </div>
  );
}

function Typewriter({ text, delay }: { text: string, delay: number }) {
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const timer = setTimeout(() => setVisible(true), delay);
    return () => clearTimeout(timer);
  }, [delay]);

  if (!visible) return null;
  return (
    <motion.span 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="block"
    >
      {text}
    </motion.span>
  );
}